prompt --application/deployment/install/install_db_objects
begin
--   Manifest
--     INSTALL: INSTALL-DB Objects
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.11'
,p_default_workspace_id=>10135125799703166
,p_default_application_id=>275
,p_default_id_offset=>80028336778020283
,p_default_owner=>'DEV_USER'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(677189755832282950)
,p_install_id=>wwv_flow_imp.id(51419834312307479430)
,p_name=>'DB Objects'
,p_sequence=>10
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'CREATE TABLE NL2SQL_CONVERSATIONS ',
'   (	ID VARCHAR2(4000 BYTE), ',
'	SUMMARY VARCHAR2(4000 CHAR), ',
'	USERNAME VARCHAR2(100 CHAR), ',
'	STARTED_ON TIMESTAMP (6), ',
'	 CONSTRAINT NL_CONV_ID_PK PRIMARY KEY (ID)',
');',
'',
'CREATE TABLE NL2SQL_PROMPTS ',
'   (	ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, ',
'	CONV_ID VARCHAR2(4000 BYTE) NOT NULL ENABLE, ',
'	PROMPT VARCHAR2(4000 CHAR), ',
'	RESPONSE CLOB, ',
'	ASKED_ON TIMESTAMP (6), ',
'	SHOWSQL VARCHAR2(4000 BYTE), ',
'	FEEDBACK_COMMENTS VARCHAR2(4000 BYTE), ',
'	FEEDBACK VARCHAR2(100 BYTE), ',
'	PROFILE VARCHAR2(100 BYTE), ',
'	TABULAR_RESPONSE CLOB, ',
'	 CONSTRAINT NL_PROMPT_ID_PK PRIMARY KEY (ID)',
'  );'))
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(677190037916282959)
,p_script_id=>wwv_flow_imp.id(677189755832282950)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'NL2SQL_CONVERSATIONS'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(677189895427282959)
,p_script_id=>wwv_flow_imp.id(677189755832282950)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'NL2SQL_PROMPTS'
);
wwv_flow_imp.component_end;
end;
/
